apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-configmap
data:
  RELEASE_NAME: {{ .Release.Name }}
  RAILS_ENV: {{ .Values.railsEnv }}
  SECRET_KEY_BASE: {{ .Values.secretKey }}
  RABBITMQ_USERNAME: {{ .Values.rabbitmq.auth.username }}
  RABBITMQ_PASSWORD: {{ .Values.rabbitmq.auth.password }}
  FIREBASE_API_KEY: {{ .Values.firebase_api_key }}
  HMAC_SECRET: {{ .Values.hmac_secret }}
  RAILS_LOG_TO_STDOUT: enabled