production:
  clients:
    default:
      uri: <%= MongoidUriBuilder.build(database_name: "user_service_production") %>

development:
  clients:
    default:
      uri: <%= MongoidUriBuilder.build(database_name: "user_service_development") %>

test:
  clients:
    default:
      uri: <%= MongoidUriBuilder.build(database_name: "user_service_test") %>
